# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # image accueil
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [150, 205], mode: inset } #outbound
                background: { size: [150, 205], position: center, color: '#ffffff'}
